name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_PATH: ${{ secrets.APP_PATH }}
          LARAVEL_ENV_ENCRYPTION_KEY: ${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: APP_PATH,LARAVEL_ENV_ENCRYPTION_KEY
          script: |
            set -e
            cd "$APP_PATH"
            git checkout .
            git clean -df
            git pull
            php artisan env:decrypt --force
            chmod 600 .env
            composer install \
              --no-dev \
              --optimize-autoloader \
              --no-interaction
            php artisan optimize:clear
            php artisan migrate --force
            php artisan optimize
